version: '2'
services:
  mysql:
    build: ../images/mysql
    environment:
     - MYSQL_ROOT_PASSWORD=adminpw
    ports:
     - "3306:3306"
  phpmyadmin:
    build: ../images/phpmyadmin
    environment:
     - MYSQL_ROOT_PASSWORD=adminpw
    ports:
     - "6060:80"
    links:
     - mysql:db
  springserver:
    build: ../images/springserver
    ports:
     - "8080:8080"
    links:
     - mysql:db
  demoapplication:
    build: ../images/demoapplication
    ports:
     - "80:80"
    links:
     - springserver:gamificationserver