FROM openjdk:8-jre
MAINTAINER Ciani Antony <antony.ciani@heig-vd.com>

COPY amtGamification-1.0.0.jar /gamification/amtGamification-1.0.0.jar

CMD ["java", "-jar", "/gamification/amtGamification-1.0.0.jar"]